name: Node CI+CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - run: npm install
    - run: npm run build

    - name: Copy to production server
      uses: garygrossgarten/github-action-scp@release
      with:
        local: dist
        remote: /var/www/wordpress/wp-content/themes/bike-sharing-theme/dist
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        privateKey: ${{ secrets.privateKey }}
