name: PHP CI CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
#     - name: Install dependencies
#       run: composer install
      
#     - name: Build
#       run: composer dump-autoload -o

    - name: Deploy to Production Server
      uses: appleboy/scp-action@master
      with:
        local: "*.php,style.css"
        target: "/var/www/html/wordpress/wp-content/themes/bike-sharing-theme/"
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.privateKey }}
